version: '3.1'
# Postgres service
services:
  postgresdb:
    image: postgres:latest
    environment:
      POSTGRES_USER: ecommerce_user
      POSTGRES_PASSWORD: secretPassw0rd10
      POSTGRES_DB: ecommerce
    networks:
      - airflow
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./data:/data
      - ./infrasetup/init.sql:/docker-entrypoint-initdb.d/init.sql

  webserver: 
    environment:
      AIRFLOW__CORE__TEST_CONNECTION: 'Enabled'

