ecommerce_project:
  outputs:
    dev:
      dataset: capstone_data1
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /Users/micahonyedikachitobias/Desktop/Capstone_Project/include/gcs/credential.json
      location: US
      method: service-account
      priority: interactive
      project: capstone-project-431620
      threads: 1
      type: bigquery
    prod:
      dataset: capstone_data_prod
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /Users/micahonyedikachitobias/Desktop/Capstone_Project/include/gcs/credential.json
      location: US
      method: service-account
      priority: interactive
      project: capstone-project-431620
      threads: 1
      type: bigquery
  target: prod
    